locals {
  storage_account_length = length(var.sub) < 6 ? 14 : 20
}

output "standard" {
  description = "Return list of calculated standard names for deployment of Azure resources"
  value = {
    resource-group  = lower(var.application_id != "" ? "rg-azu${var.location-map[var.location]}-${var.application_id}-${var.context}-${var.environment}-${var.inc}" : "rg-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    virtual-network = lower(var.application_id != "" ? "vnet-azu${var.location-map[var.location]}-${var.routing_domain}-${var.application_id}-${var.environment}-${var.inc}" : "vnet-azu${var.location-map[var.location]}-${var.routing_domain}-${var.environment}-${var.inc}")
    subnet          = lower("snet-azu${var.location-map[var.location]}-${var.security_zone}-${var.subnet_cidr}")
    #subnet                     = lower("snet-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    route-table                          = lower(var.application_id != "" ? "rt-azu${var.location-map[var.location]}-${var.routing_domain}-${var.application_id}-${var.context}-${var.environment}-${var.inc}" : "rt-azu${var.location-map[var.location]}-${var.routing_domain}-${var.context}-${var.environment}-${var.inc}")
    application-security-group           = lower(var.application_id != "" ? "asg-azu${var.location-map[var.location]}-${var.application_id}-${var.context}-${var.environment}-${var.inc}" : "asg-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    key-vault                            = lower(var.application_id != "" ? "kv${var.location-map[var.location]}${var.application_id}${var.environment}${var.inc}" : "kv${var.location-map[var.location]}${var.context}${var.environment}${var.inc}")
    network-security-group               = lower(var.application_id != "" ? "nsg-azu${var.location-map[var.location]}-${var.routing_domain}-${var.application_id}-${var.security_zone}-${var.environment}-${var.inc}" : "nsg-azu${var.location-map[var.location]}-${var.routing_domain}-${var.security_zone}-${var.environment}-${var.inc}")
    public-ip-address                    = lower("pip-azu${var.location-map[var.location]}-${var.routing_domain}-${var.context}-${var.environment}-${var.inc}")
    local-network-gateway                = lower("lgw-azu${var.location-map[var.location]}-${var.routing_domain}-${var.environment}-${var.context}-${var.inc}")
    vnet-gateway-connection              = lower(var.context != "" ? "con-azu${var.location-map[var.location]}-${var.routing_domain}-${var.environment}-${var.context}-${var.inc}" : "con-azu${var.location-map[var.location]}-${var.routing_domain}-${var.environment}-${var.inc}")
    vnet-gateway                         = lower("vgw-azu${var.location-map[var.location]}-${var.routing_domain}-${var.environment}-${var.inc}")
    ip-group                             = lower(var.application_id != "" ? "ipg-azu${var.location-map[var.location]}-${var.application_id}-${var.environment}-${var.inc}" : "ipg-azu${var.location-map[var.location]}-${var.routing_domain}-${var.environment}-${var.inc}")
    bastion                              = lower("bst-azu${var.location-map[var.location]}-${var.routing_domain}-${var.environment}-${var.inc}")
    firewall                             = lower("afw-azu${var.location-map[var.location]}-${var.routing_domain}-${var.environment}-${var.inc}")
    firewall-policy                      = lower("afwp-azu${var.location-map[var.location]}-${var.routing_domain}-${var.environment}-${var.inc}")
    nva-fgt                              = lower("nva-fgt-azu${var.location-map[var.location]}-${var.application_id}-${var.context}-${var.environment}-${var.inc}")
    nva-fgt-nic                          = lower("nva-fgt-nic-${var.location-map[var.location]}-${var.application_id}-${var.context}-${var.environment}-${var.inc}")
    private-dns-resolver                 = lower("dnspr-azu${var.location-map[var.location]}-${var.routing_domain}-${var.environment}-${var.inc}")
    inbound-endpoints-dns                = lower("in-azu${var.location-map[var.location]}-${var.routing_domain}-${var.environment}-${var.inc}")
    outbound-endpoints-dns               = lower("out-azu${var.location-map[var.location]}-${var.routing_domain}-${var.environment}-${var.inc}")
    dns-forwarding-ruleset               = lower("dnsfrs-azu${var.location-map[var.location]}-${var.routing_domain}-${var.environment}-${var.inc}")
    event-hub                            = lower("evh-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    event-hub-namespace                  = lower("evhns-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    eventhub-ns-authorization-rule       = lower("evhnsar-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    eventhub-authorization-rule          = lower("evhar-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    event-grid-system-topic              = lower("evgst-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    event-grid-system-topic-subscription = lower("evsts-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    logic-app                            = lower("logic-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    storage-account                      = lower("st${var.location-map[var.location]}${var.local_market_shortcut}${var.context}${var.environment}${var.inc}")
    log-analytics-workspace              = lower("law-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    api-connection                       = lower("api-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    virtual-machine                      = lower(var.local_market != "" ? "vm${var.location-map[var.location]}${var.local_market}${var.context}${var.inc}" : "vm${var.location-map[var.location]}${var.context}${var.environment}${var.inc}")
    ddos-protection-plan                 = lower("ddos-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    load-balancer                        = lower(var.routing_domain != "" ? "lbi-azu${var.location-map[var.location]}-${var.routing_domain}-${var.context}-${var.environment}-${var.inc}" : "ilb-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    shared-image-gallery                 = lower("sig${var.environment}${var.location-map[var.location]}${var.context}")
    keyvault-key                         = lower("kvk-azu${var.location-map[var.location]}-cmk${var.key_func}-${var.environment}-${var.inc}")
    express-route-circuit                = lower("erc-azu${var.location-map[var.location]}-${var.routing_domain}-${var.environment}-${var.inc}")
    data-disk                            = lower(var.local_market != "" ? "vm${var.location-map[var.location]}${var.local_market}${var.context}${var.inc}-datadisk-${var.data_disk_inc}" : "vm${var.location-map[var.location]}${var.context}${var.environment}${var.inc}-datadisk-${var.data_disk_inc}")
    os-disk                              = lower("vm-${var.location-map[var.location]}-${var.context}${can(regex("vg", var.context)) ? "" : var.environment}${var.inc}-osdisk")
    private-endpoint                     = lower("pep-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    managed_devops_pool                  = lower("mdp-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    automation_account                   = lower("aa-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    dev_center                           = lower("dc-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}") #name cannot exceed 26 characters
    virtual-machine-scale-set            = lower("vmss${var.location-map[var.location]}${var.context}${var.environment}${var.inc}")
    auto-scaling                         = lower("scaling${var.location-map[var.location]}${var.context}${var.environment}${var.inc}")
    nat_gateway                          = lower("natgw${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    disk-encryption-set                  = lower(var.application_id != "" ? "des-azu${var.location-map[var.location]}-${var.application_id}-${var.environment}-${var.inc}" : "des-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    app-service-plan                     = lower("asp-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    web-app                              = lower("app-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    function-app                         = lower("func-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    dashboard                            = lower("dash-azu${var.location-map[var.location]}-mon-${var.environment}-${var.inc}")
    mysql-db-server                      = lower("mysql-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    sql-managed-instance                 = lower("sqlmi-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    sql-database                         = lower("sqldb-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    sql-server                           = lower("sqlsrv-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    app-gateway                          = lower("agw${var.location-map[var.location]}${var.local_market_shortcut}${var.context}${var.environment}${var.inc}")
    agw-front-end-pvt                    = lower("agfe-pvt-${var.context}-ipv4-${var.inc}")
    agw-front-end-pub                    = lower("agfe-pub-${var.context}-ipv4-${var.inc}")
    agw-backend-pool                     = lower("agbp-${var.context}-${var.agwbe_port}-${var.inc}")
    agw-health-probe                     = lower("aghp-${var.context}-${var.agwhp_type}-${var.inc}")
    agw-routing-rule                     = lower("agr-${var.context}-${var.agwrrl_type}-${var.inc}")
    agw-backend-settings                 = lower("agbs-${var.context}-${var.agwbs_type}-${var.inc}")
    agw-listener                         = lower("ls-agw-${var.context}-${var.agwls_port}-${var.inc}")
    agw-rewrite-set                      = lower("rws-${var.context}-${var.inc}")
  }
}
