name: Terraform Plan Template

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to plan (lab/nlv/lv)'
        required: true
        type: string
      working-directory:
        description: 'Working directory'
        required: false
        type: string
        default: '.'
    secrets:
      AZURE_AD_CLIENT_ID:
        required: true
      AZURE_AD_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_AD_TENANT_ID:
        required: true
    outputs:
      plan-output:
        description: "Terraform plan output"
        value: ${{ jobs.terraform-plan.outputs.plan-output }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      plan-output: ${{ steps.plan.outputs.stdout }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
        terraform_wrapper: false
        
    - name: Configure Azure credentials
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_AD_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_AD_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_AD_TENANT_ID }}"
          }
    
    - name: Update main.tf for environment
      run: |
        sed -i 's/lab-customer-config.yml/${{ inputs.environment }}-customer-config.yml/g' main.tf
      working-directory: ${{ inputs.working-directory }}
    
    - name: Terraform Init
      run: terraform init
      working-directory: ${{ inputs.working-directory }}
      
    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -no-color -out=tfplan
        terraform show -no-color tfplan
      working-directory: ${{ inputs.working-directory }}