name: Terraform Apply Template

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to apply (lab/nlv/lv)'
        required: true
        type: string
      working-directory:
        description: 'Working directory'
        required: false
        type: string
        default: '.'
    secrets:
      AZURE_AD_CLIENT_ID:
        required: true
      AZURE_AD_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_AD_TENANT_ID:
        required: true

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}-apply # 🔒 This creates the approval gate!
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
        
    - name: Configure Azure credentials
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_AD_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_AD_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_AD_TENANT_ID }}"
          }
    
    - name: Update main.tf for environment
      run: |
        sed -i 's/lab-customer-config.yml/${{ inputs.environment }}-customer-config.yml/g' main.tf
      working-directory: ${{ inputs.working-directory }}
    
    - name: Terraform Init
      run: terraform init
      working-directory: ${{ inputs.working-directory }}
      
    - name: Terraform Plan
      run: terraform plan -no-color -out=tfplan
      working-directory: ${{ inputs.working-directory }}
      
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ${{ inputs.working-directory }}
      
    - name: Output deployment results
      run: terraform output -json
      working-directory: ${{ inputs.working-directory }}
      
    - name: Comment deployment success
      if: success()
      uses: actions/github-script@v7
      with:
        script: |
          const output = `#### Terraform Apply Successful ✅ \`${{ inputs.environment }}\`
          
          🚀 **Deployment completed successfully!**
          
          - **Environment**: \`${{ inputs.environment }}\`
          - **Branch**: \`${{ github.ref_name }}\`
          - **Commit**: \`${{ github.sha }}\`
          - **Actor**: @${{ github.actor }}
          
          *Time: $(date)*`;
          
          if (context.payload.pull_request) {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
          }